import React from 'react';
import { ArrowLeft } from 'lucide-react';

const TermsOfService = ({ onBack }) => {
    return (
        <div className="min-h-screen bg-white font-sans text-oxford-blue">
            <div className="max-w-3xl mx-auto px-6 py-20">
                <button
                    onClick={onBack}
                    className="flex items-center gap-2 text-oxford-blue/60 hover:text-oxford-blue transition-colors mb-12 font-medium"
                >
                    <ArrowLeft size={20} />
                    Back
                </button>

                <h1 className="text-4xl font-serif font-bold text-oxford-blue mb-4">Terms of Service</h1>
                <p className="text-oxford-blue/60 mb-12">Last Updated: January 15, 2026</p>

                <div className="space-y-12">
                    <section>
                        <h2 className="text-2xl font-bold text-oxford-blue mb-4">1. Use of Service</h2>
                        <ul className="list-disc pl-6 space-y-2 text-oxford-blue/80 leading-relaxed">
                            <li>ScholarGo is an AI-based essay analysis tool for educational purposes.</li>
                            <li>You are prohibited from using this service for illegal actions, including but not limited to academic fraud or systematic plagiarism.</li>
                            <li>You are fully responsible for the security of the Google account you use to log in.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-oxford-blue mb-4">2. Content Ownership</h2>
                        <ul className="list-disc pl-6 space-y-2 text-oxford-blue/80 leading-relaxed">
                            <li>You retain full rights to the essay text you upload to ScholarGo.</li>
                            <li>By using our service, you grant ScholarGo permission to process such data solely for the purpose of providing analysis results.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-oxford-blue mb-4">3. Limitation of Liability (AI Disclaimer)</h2>
                        <ul className="list-disc pl-6 space-y-2 text-oxford-blue/80 leading-relaxed">
                            <li>The analysis provided by ScholarGo is generated by artificial intelligence (AI) and may contain errors.</li>
                            <li>ScholarGo does not guarantee scholarship acceptance or 100% accuracy of the analysis results.</li>
                            <li>The use of AI analysis results in the final essay draft is the sole responsibility of the user.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-oxford-blue mb-4">4. Account and Data Policy</h2>
                        <ul className="list-disc pl-6 space-y-2 text-oxford-blue/80 leading-relaxed">
                            <li>We reserve the right to limit access to the free plan (Free Plan) in accordance with operational policies.</li>
                            <li>You may delete your chat history data at any time through the features available in the application.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-oxford-blue mb-4">5. Changes to Terms</h2>
                        <p className="text-oxford-blue/80 leading-relaxed">
                            We may update these terms at any time to adapt to new features or applicable legal regulations.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
